route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email_configs'
receivers:
  - name: "email"
    email_configs:
      - to: "raghudevopsb79@gmail.com"
        from: "raghudevopsb79@gmail.com"
        smarthost: "email-smtp.us-east-1.amazonaws.com"
        auth_username: "{{secrets.smtp_username}}"
        auth_password: "{{secrets.smtp_password}}"
        require_tls: true

